### Used Car(Toyota) data analysis for maching learning with python

#### References:
dataset source: https://www.kaggle.com/aishwaryamuthukumar/cars-dataset-audi-bmw-ford-hyundai-skoda-vw

#### import required libraries

In [86]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#### Load data

In [58]:
df = pd.read_csv("toyota.csv")

display(df.head())
display(df.tail())
print(df.shape)

model  year  price transmission  mileage fuelType   mpg  engineSize
0   GT86  2016  16000       Manual    24089   Petrol  36.2         2.0
1   GT86  2017  15995       Manual    18615   Petrol  36.2         2.0
2   GT86  2015  13998       Manual    27469   Petrol  36.2         2.0
3   GT86  2017  18998       Manual    14736   Petrol  36.2         2.0
4   GT86  2017  17498       Manual    36284   Petrol  36.2         2.0

model  year  price transmission  mileage fuelType   mpg  \
6733              IQ  2011   5500    Automatic    30000   Petrol  58.9   
6734   Urban Cruiser  2011   4985       Manual    36154   Petrol  50.4   
6735   Urban Cruiser  2012   4995       Manual    46000   Diesel  57.6   
6736   Urban Cruiser  2011   3995       Manual    60700   Petrol  50.4   
6737   Urban Cruiser  2011   4495       Manual    45128   Petrol  50.4   

      engineSize  
6733         1.0  
6734         1.3  
6735         1.4  
6736         1.3  
6737         1.3

(6738, 8)


In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 8 columns):
model           6738 non-null object
year            6738 non-null int64
price           6738 non-null int64
transmission    6738 non-null object
mileage         6738 non-null int64
fuelType        6738 non-null object
mpg             6738 non-null float64
engineSize      6738 non-null float64
dtypes: float64(2), int64(3), object(3)
memory usage: 342.2+ KB


In [60]:
df.describe()

year         price        mileage          mpg   engineSize
count  6738.000000   6738.000000    6738.000000  6738.000000  6738.000000
mean   2016.748145  12522.391066   22857.413921    63.042223     1.471297
std       2.204062   6345.017587   19125.464147    15.836710     0.436159
min    1998.000000    850.000000       2.000000     2.800000     0.000000
25%    2016.000000   8290.000000    9446.000000    55.400000     1.000000
50%    2017.000000  10795.000000   18513.000000    62.800000     1.500000
75%    2018.000000  14995.000000   31063.750000    69.000000     1.800000
max    2020.000000  59995.000000  174419.000000   235.000000     4.500000

#### dealing with catagorical value

In [61]:
df["model"].value_counts()

 Yaris            2122
 Aygo             1961
 Auris             712
 C-HR              479
 RAV4              473
 Corolla           267
 Prius             232
 Avensis           115
 Verso             114
 Hilux              86
 GT86               73
 Land Cruiser       51
 PROACE VERSO       15
 Supra              12
 Camry              11
 IQ                  8
 Urban Cruiser       4
 Verso-S             3
Name: model, dtype: int64

In [62]:
df["transmission"].value_counts()

Manual       3826
Automatic    2657
Semi-Auto     254
Other           1
Name: transmission, dtype: int64

In [63]:
df["fuelType"].value_counts()

Petrol    4087
Hybrid    2043
Diesel     503
Other      105
Name: fuelType, dtype: int64

In [64]:
print(df["model"].unique())
print(len(df["model"].unique()))

print(df["transmission"].unique())
print(len(df["transmission"].unique()))

print(df["fuelType"].unique())
print(len(df["fuelType"].unique()))

[' GT86' ' Corolla' ' RAV4' ' Yaris' ' Auris' ' Aygo' ' C-HR' ' Prius'
 ' Avensis' ' Verso' ' Hilux' ' PROACE VERSO' ' Land Cruiser' ' Supra'
 ' Camry' ' Verso-S' ' IQ' ' Urban Cruiser']
18
['Manual' 'Automatic' 'Semi-Auto' 'Other']
4
['Petrol' 'Other' 'Hybrid' 'Diesel']
4


#### Label Encoding

In [65]:
LE = LabelEncoder()
df["transmission_"] = LE.fit_transform(df["transmission"])
print(LE.classes_)
print(df["transmission_"].unique())

df["model_"] = LE.fit_transform(df["model"])
print(LE.classes_)
print(df["model_"].unique())

df["fuelType_"] = LE.fit_transform(df["fuelType"])
print(LE.classes_)
print(df["fuelType_"].unique())

display(df.sample(10))
print(df.shape)

['Automatic' 'Manual' 'Other' 'Semi-Auto']
[1 0 3 2]
[' Auris' ' Avensis' ' Aygo' ' C-HR' ' Camry' ' Corolla' ' GT86' ' Hilux'
 ' IQ' ' Land Cruiser' ' PROACE VERSO' ' Prius' ' RAV4' ' Supra'
 ' Urban Cruiser' ' Verso' ' Verso-S' ' Yaris']
[ 6  5 12 17  0  2  3 11  1 15  7 10  9 13  4 16  8 14]
['Diesel' 'Hybrid' 'Other' 'Petrol']
[3 2 1 0]


model  year  price transmission  mileage fuelType   mpg  engineSize  \
2208     Yaris  2014   5795       Manual    39000   Petrol  58.0         1.3   
965      Yaris  2017   9440       Manual    20115   Petrol  58.9         1.5   
1486     Yaris  2016   8999       Manual    25826   Petrol  55.0         1.3   
4633      Aygo  2016   6000       Manual    23530   Petrol  69.0         1.0   
1508     Yaris  2017   9795       Manual    24114   Petrol  55.0         1.3   
1393     Yaris  2017   8995       Manual    20295   Petrol  65.7         1.0   
2713     Yaris  2005   2795       Manual    48830   Petrol  50.4         1.3   
258    Corolla  2020  25998    Automatic     5000   Hybrid  53.3         2.0   
3233     Auris  2014  10999    Automatic    42015   Hybrid  74.3         1.8   
2194     Yaris  2018  13885    Automatic    11656   Hybrid  76.3         1.5   

      transmission_  model_  fuelType_  
2208              1      17          3  
965               1      17          3  
1486              1      17          3  
4633              1       2          3  
1508              1      17          3  
1393              1      17          3  
2713              1      17          3  
258               0       5          1  
3233              0       0          1  
2194              0      17          1

(6738, 11)


In [81]:
####The column numbers are not increase much in Label Encoding

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6738 entries, 0 to 6737
Data columns (total 11 columns):
model            6738 non-null object
year             6738 non-null int64
price            6738 non-null int64
transmission     6738 non-null object
mileage          6738 non-null int64
fuelType         6738 non-null object
mpg              6738 non-null float64
engineSize       6738 non-null float64
transmission_    6738 non-null int32
model_           6738 non-null int32
fuelType_        6738 non-null int32
dtypes: float64(2), int32(3), int64(3), object(3)
memory usage: 421.2+ KB


#### One-hot Encoding

In [67]:
df_transmission = pd.get_dummies(df["transmission"])
df_transmission = df_transmission.drop("Other", axis=1)
display(df_transmission.sample(10))

Automatic  Manual  Semi-Auto
6151          1       0          0
4597          0       1          0
4389          0       1          0
2592          0       1          0
1096          0       1          0
325           1       0          0
4578          0       1          0
6346          0       1          0
2454          0       1          0
1616          1       0          0

In [68]:
df_model = pd.get_dummies(df["model"])
display(df_model.sample(10))

Auris   Avensis   Aygo   C-HR   Camry   Corolla   GT86   Hilux   IQ  \
4016       0         0      1      0       0         0      0       0    0   
5774       0         0      0      1       0         0      0       0    0   
3585       1         0      0      0       0         0      0       0    0   
1498       0         0      0      0       0         0      0       0    0   
1405       0         0      0      0       0         0      0       0    0   
826        0         0      0      0       0         0      0       0    0   
6089       0         0      0      0       0         0      0       0    0   
4365       0         0      1      0       0         0      0       0    0   
2802       0         0      0      0       0         0      0       0    0   
611        0         0      0      0       0         0      0       0    0   

       Land Cruiser   PROACE VERSO   Prius   RAV4   Supra   Urban Cruiser  \
4016              0              0       0      0       0               0   
5774              0              0       0      0       0               0   
3585              0              0       0      0       0               0   
1498              0              0       0      0       0               0   
1405              0              0       0      0       0               0   
826               0              0       0      0       0               0   
6089              0              0       1      0       0               0   
4365              0              0       0      0       0               0   
2802              0              0       0      0       0               0   
611               0              0       0      1       0               0   

       Verso   Verso-S   Yaris  
4016       0         0       0  
5774       0         0       0  
3585       0         0       0  
1498       0         0       1  
1405       0         0       1  
826        0         0       1  
6089       0         0       0  
4365       0         0       0  
2802       0         0       1  
611        0         0       0

In [69]:
df_fuelType = pd.get_dummies(df["fuelType"])
display(df_fuelType.sample(10))

Diesel  Hybrid  Other  Petrol
3357       0       1      0       0
5782       0       1      0       0
2391       0       0      0       1
3942       0       0      0       1
4013       0       0      0       1
5037       0       0      0       1
3198       0       1      0       0
6693       1       0      0       0
3590       0       1      0       0
257        0       0      0       1

In [70]:
print(df.shape)
df = pd.get_dummies(df)

display(df.sample(10))
print(df.shape)

(6738, 11)


year  price  mileage   mpg  engineSize  transmission_  model_  \
2937  2016  14960    28121  70.6         1.8              0       0   
1685  2013   5998    42741  51.4         1.3              1      17   
80    2019  20998     8442  85.6         1.8              0       5   
3119  2014  11495    33401  72.4         1.8              0       0   
5664  2019  23995    10880  74.3         1.8              0       3   
1482  2017  10970     3417  58.0         1.3              0      17   
2088  2017  11326    21916  60.1         1.5              0      17   
4075  2017   6995    10000  69.0         1.0              1       2   
4350  2018   7691    17290  68.9         1.0              1       2   
3372  2017  16791    29850  78.5         1.8              0       0   

      fuelType_  model_ Auris  model_ Avensis       ...         \
2937          1             1               0       ...          
1685          3             0               0       ...          
80            1             0               0       ...          
3119          1             1               0       ...          
5664          1             0               0       ...          
1482          3             0               0       ...          
2088          3             0               0       ...          
4075          3             0               0       ...          
4350          3             0               0       ...          
3372          1             1               0       ...          

      model_ Verso-S  model_ Yaris  transmission_Automatic  \
2937               0             0                       1   
1685               0             1                       0   
80                 0             0                       1   
3119               0             0                       1   
5664               0             0                       1   
1482               0             1                       1   
2088               0             1                       1   
4075               0             0                       0   
4350               0             0                       0   
3372               0             0                       1   

      transmission_Manual  transmission_Other  transmission_Semi-Auto  \
2937                    0                   0                       0   
1685                    1                   0                       0   
80                      0                   0                       0   
3119                    0                   0                       0   
5664                    0                   0                       0   
1482                    0                   0                       0   
2088                    0                   0                       0   
4075                    1                   0                       0   
4350                    1                   0                       0   
3372                    0                   0                       0   

      fuelType_Diesel  fuelType_Hybrid  fuelType_Other  fuelType_Petrol  
2937                0                1               0                0  
1685                0                0               0                1  
80                  0                1               0                0  
3119                0                1               0                0  
5664                0                1               0                0  
1482                0                0               0                1  
2088                0                0               0                1  
4075                0                0               0                1  
4350                0                0               0                1  
3372                0                1               0                0  

[10 rows x 34 columns]

(6738, 34)


In [ ]:
####The column numbers are increase quit much in One-hot encoding 

#### Separating the features and target variable

In [71]:
features = ['year','mileage', 'engineSize']
target = ['price']

x = df[features]
y = df[target]

print("Shape of x = ", x.shape)
print("Shape of y = ", y.shape)

Shape of x =  (6738, 3)
Shape of y =  (6738, 1)


#### split train and test set

In [72]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(5390, 3) (1348, 3) (5390, 1) (1348, 1)


#### Linear Regression

In [73]:
model = LinearRegression()
model = model.fit(x_train, y_train)

y = m1x1 + m2x2 + m3x3 +m4x4 + c

In [74]:
coefficients = model.coef_
print(coefficients)

[[  8.53091515e+02  -7.42080602e-02   1.13380117e+04]]


In [75]:
c = model.intercept_
print(c)

[-1722949.17079021]


In [76]:
coef_df = pd.DataFrame({"features": x.columns, 
                       "coefficients": np.squeeze(coefficients)})

display(coef_df)

coefficients    features
0    853.091515        year
1     -0.074208     mileage
2  11338.011738  engineSize

#### Prediction

In [77]:
y_prd = model.predict(x_test)
print(y_prd)

[[ 27582.51671811]
 [  2122.34818917]
 [ 12188.67648397]
 ..., 
 [ 14377.73136225]
 [  7517.58461566]
 [  9033.23734053]]


In [78]:
print(y_test)

      price
381   37440
2476   4159
2855  10600
2018   8995
2185  11000
1894  11215
2641  11295
503   11995
6091  19998
2644  11295
3622  11000
2633  12491
4017  10290
5737  13998
2609   4690
2678  13990
6501  12990
1559  13195
6516  11400
4884   9995
4161   7290
5558   9370
6049  20990
1611  11998
3406  15814
1163   9995
6007  21491
4078   5795
2338  11816
6255  18799
...     ...
149   22790
6562  18495
5489  10350
453   29000
1615  12995
4816   8275
3434  13495
808   20995
3386  11342
3480  12975
1119   9990
810   19695
1129   6490
834    8998
5664  23995
5178   7000
6443  11498
2666  11990
1235  10280
1225  11250
1480   7850
1720  12436
4157   6895
5452  10495
2647  12495
4715  10800
5374   7495
1027  10790
2802   9991
3789   8298

[1348 rows x 1 columns]


#### Prediction Error

In [87]:
MAE = mean_absolute_error(y_test, y_prd)
print("MAE = ", MAE)

MSE = mean_squared_error(y_test, y_prd)
print("MSE = ", MSE)

RMSE = mean_squared_error(y_test, y_prd)
print("RMSE = ", RMSE)

r2 = r2_score(y_test, y_prd)
print("r_squared = ", r2)

MAE =  2289.05782692
MSE =  9980266.31769
RMSE =  9980266.31769
r_squared =  0.765480696041
